language: java
jdk:
  - oraclejdk8
before_install:
  - pip install --user codecov
after_success:
  - codecov
  - mvn clean test jacoco:report coveralls:report
deploy:
  provider: heroku
  api_key:
    secure: "562b649f-b673-4351-b99d-ce94c137272f"